//#!groovy

String buildShell = "${env.buildShell}"

pipeline {
    // 指定集群节点
    agent any
    // 选项
    options {
        timestamps() //日志会有时间
        skipDefaultCheckout() //删除隐式checkout scm语句
        disableConcurrentBuilds() //禁止并行
        timeout(time: 1, unit: 'HOURS') //流水线超市设置1h
    }
    // 声明全局变量
    environment {
        key = 'value'
    }
    // 流水线阶段
    stages {
        stage('Checkout') {
            steps {
                timeout(time: 5, unit: "MINUTES"){
                    checkout([$class: 'GitSCM', branches: [[name: '${tag}']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/liuzhaomax/maxblog-fe-main.git']]])
                }
            }
        }
        stage('Update GitHub') {
            steps {
                echo 'Update GitHub - SUCCESS'
            }
        }
        stage('Change Node Version') {
            steps {
                echo 'Change Node Version - SUCCESS'
            }
        }
        stage('App Version') {
            steps {
                echo 'App Version - SUCCESS'
            }
        }
        stage('Lint') {
            steps {
                echo 'Lint - SUCCESS'
            }
        }
        stage('Build') {
            steps {
                script {
                    npmHome = tool "npm" //变量名npm在jenkins全局工具里定义的
                    sh "export NODE_HOME=${npmHome} && export PATH=\$NODE_HOME/bin:\$PATH && ${npmHome}/bin/npm ${buildShell}"
                }
            }
        }
        stage('Static Analysis') {
            steps {
                echo 'Static Analysis - SUCCESS'
            }
        }
        stage('SonarQube') {
            steps {
                echo 'SonarQube - SUCCESS'
            }
        }
        stage('Nessus') {
            steps {
                echo 'Nessus - SUCCESS'
            }
        }
        stage('Build Image') {
            steps {
                echo 'Build Image - SUCCESS'
            }
        }
        stage('Git Tag') {
            steps {
                echo 'Git Tag - SUCCESS'
            }
        }
        stage('Package Config') {
            steps {
                echo 'Package Config - SUCCESS'
            }
        }
    }
}