version: '3.1'
services:
  jenkins:
    image: 'jenkins/jenkins:2.319.3-lts'
    container_name: jenkins
    privileged: true
    restart: always
    user: root
    ports:
      - '9000:8080'
      - '50000:50000'
    volumes:
      - './data:/var/jenkins_home'
      - '/usr/bin/docker:/usr/bin/docker'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/home/opc/tools/node/bin/node:/usr/bin/node'